site_name: 'Read Learn Think Make'
site_description: ''
site_author: 'kindone'
site_url: 'https://kindone.github.io'

extra_css:
  - stylesheets/extra.css
  #- https://basehold.it/12 # vertical grid

copyright: Copyright &copy; 2023 - 2024 Kindone
theme:
  name: material
  font:
    text: 'Noto Sans KR'
    code: 'Inconsolata'
  palette:
    primary: blue grey
    accent: indigo
  logo: images/android-chrome-192x192.png
  icon:
    logo: material/leaf
  favicon: images/favicon-32x32.png
  features:
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.indexes
    #- navigation.path (unsupported)
    - navigation.sections
    - navigation.top
    - navigation.expand
    - toc.follow
    - search.highlight
    - search.suggest

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.magiclink
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - attr_list
  - meta
  - footnotes
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

plugins:
  - search
  - git-revision-date-localized
  - kroki:
      DownloadImages: true
  - extra-sass
  - blogging:
      dirs:
        - blog
      categories:
        - name: draft
          dirs:
            - draft
      #full_content: true
      locale: en
      time_format: '%Y-%m-%d %H:%M:%S'
      meta_time_format: '%Y-%m-%d %H:%M:%S'

nav:
  - 'Articles and Projects':
    #- 'articles/index.md'
    - '생각의 모래성을 쌓기':
      - 'articles/sandcastle/index.md'
      - '생각을 표현하기':
        - 'articles/sandcastle/drawing.md'
  - blog.md
  - draft.md



