site_name: 'Read Learn Think Make'
site_description: ''
site_author: 'kindone'
site_url: 'https://kindone.github.io'

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  font:
    text: 'Gothic A1'
    code: 'Inconsolata'
  palette:
    primary: green
    accent: light green
  logo: images/android-chrome-192x192.png
  icon:
    logo: material/leaf
  favicon: images/favicon-32x32.png
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    #- navigation.path (unsupported)
    #- navigation.sections
    - navigation.top
    - navigation.expand
    - toc.follow
    - search.highlight
    - search.suggest

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.magiclink
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - attr_list
  - meta
  - footnotes
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true

plugins:
  - search
  - git-revision-date-localized
  - kroki:
      DownloadImages: true
  - blogging:
      dirs:
        - blog
      categories:
        - name: draft
          dirs:
            - draft
      #full_content: true
      locale: en
      time_format: '%Y-%m-%d %H:%M:%S'
      meta_time_format: '%Y-%m-%d %H:%M:%S'

nav:
  - 'Articles and Projects':
    #- 'articles/index.md'
    - 'Project Sand Castle':
      - 'articles/sandcastle/index.md'
  - blog.md
  - draft.md



